import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import NextTopLoader from "nextjs-toploader";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ChakraProvider> */}
      <body className={inter.className}>
        <Toaster position="top-right" reverseOrder={false} />
        <NextTopLoader color="#4983f6" />
        {children}
      </body>
      {/* </ChakraProvider> */}
    </html>
  );
}
